name = "charizard"
national_pokedex_number = 6
poketype = [["Fire", "Flying"]]
image_url = "https://bulbapedia.bulbagarden.net/wiki/File:0006Charizard.png"

[stats]
hp = 78
atk = 84
def = 78
spatk = 109
spdef = 85
spd = 100
